# Generated by Django 5.2.4 on 2025-08-10 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiquiz', '0002_userresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'ordering': ['-answered_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresponse',
            name='difficulty',
            field=models.CharField(blank=True, db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='question_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='time_taken',
            field=models.FloatField(blank=True, help_text='Time taken in seconds', null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='MCQ', max_length=3),
        ),
    ]
